config/routes.rb
GTD::Application.routes.draw do
  resources :zones

  resources :projects

  resources :tasks
  match 'complete_task/:id' => 'tasks#complete', :as => :complete_task

  root :to => "tasks#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :zone

  scope :inbox, where("tasks.project_id IS NULL OR tasks.zone_id IS NULL").where(:done => false)
  default_scope order("done, due_date ASC")
end

app/models/zone.rb
class Zone < ActiveRecord::Base
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :find_projects
  before_filter :find_zones
  before_filter :inbox_count

private

  def find_projects
    @projects = Project.all
  end

  def find_zones
    @zones = Zone.all
  end

  def inbox_count
    @inbox_count = Task.inbox.count
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(root_path) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    if params[:view] == "inbox"
      @tasks = Task.inbox
    else
      @tasks = Task.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])

    if @task.save
      redirect_to root_path
    else
      render :action => "edit"
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        redirect_to root_path
      else
        render :action => "edit"
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end

  def complete
    @task = Task.find(params[:id])
    @task.update_attribute(:done, true)

    redirect_to root_path
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  # GET /zones/1
  # GET /zones/1.xml
  def show
    @zone = Zone.find(params[:id])
    @tasks = @zone.tasks

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @zone }
    end
  end

  # GET /zones/new
  # GET /zones/new.xml
  def new
    @zone = Zone.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @zone }
    end
  end

  # GET /zones/1/edit
  def edit
    @zone = Zone.find(params[:id])
  end

  # POST /zones
  # POST /zones.xml
  def create
    @zone = Zone.new(params[:zone])

    respond_to do |format|
      if @zone.save
        format.html { redirect_to(@zone, :notice => 'Zone was successfully created.') }
        format.xml  { render :xml => @zone, :status => :created, :location => @zone }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @zone.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /zones/1
  # PUT /zones/1.xml
  def update
    @zone = Zone.find(params[:id])

    respond_to do |format|
      if @zone.update_attributes(params[:zone])
        format.html { redirect_to(@zone, :notice => 'Zone was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @zone.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.xml
  def destroy
    @zone = Zone.find(params[:id])
    @zone.destroy

    respond_to do |format|
      format.html { redirect_to(root_path) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GTD</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <h1>To Do</h1>
  </div>
  <div class="container-fluid">
      <div class="sidebar">
        <p>
          <%= link_to "Inbox", tasks_path(:view => "inbox") %>
          <%= "(#{@inbox_count})" if @inbox_count > 0 %>
        </p>
        <p><%= link_to "Today", tasks_path %></p>
        <p>Projects:</p>
        <ul>
          <% @projects.each do |project| %>
            <li><%= link_to project.name, project %></li>
          <% end %>
          <li><%= link_to "Add a project", new_project_path %></li>
        </ul>
        <p>Zones:</p>
        <ul>
          <% @zones.each do |zone| %>
            <li><%= link_to zone.name, zone %></li>
          <% end %>
          <li><%= link_to "Add a zone", new_zone_path %></li>
        </ul>

      </div>
      <div class="content">
        <%= yield %>
      </div>
    </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :name %>
    <div class="input">
      <%= f.text_field :name %>      
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @project.name %></h2>

<table>
  <tr>
    <th></th>
    <th></th>
    <th>Due date</th>
    <th>Project</th>
    <th>Zone</th>
    <th></th>
    <th></th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <th>
        <% if task.done? %>
          [&#10003;]
        <% else %>
          <%= link_to "[ ]", complete_task_path(:id => task.id) %>
        <% end %>
      </th>

      <td><%= task.name %></td>
      <td>
        <% if task.due_date.past? %>
          <%= time_ago_in_words(task.due_date) %> ago
        <% else %>
          in <%= time_ago_in_words(task.due_date) %>
        <% end %>
      </td>
      <td><%= link_to(task.project.name, task.project) if task.project %></td>
      <td><%= link_to(task.zone.name, task.zone) if task.zone %></td>
      <td><%= link_to 'Edit', edit_task_path(task) %></td>
      <td><%= link_to 'Delete', task, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :name %>
    <div class="input">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :due_date %>
    <div class="input">
      <%= f.date_select :due_date %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :project_id %>
    <div class="input">
      <%= f.collection_select(:project_id, Project.all, :id, :name, :prompt => true) %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :zone_id %>
    <div class="input">
      <%= f.collection_select(:zone_id, Zone.all, :id, :name, :prompt => true) %>
    </div>  
  </div>

  <div class="actions">
    <%= f.submit :class => "btn primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Due date</th>
    <th>Project</th>
    <th>Zone</th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <th>
      <% if task.done? %>
        [&#10003;]
      <% else %>
        <%= link_to "[ ]", complete_task_path(:id => task.id) %>
      <% end %>
    </th>

    <td><%= task.name %></td>
    <td>
      <% if task.due_date.past? %>
        <%= time_ago_in_words(task.due_date) %> ago
      <% else %>
        in <%= time_ago_in_words(task.due_date) %>
      <% end %>
    </td>
    <td><%= task.project.name if task.project %></td>
    <td><%= task.zone.name if task.zone %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Delete', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Due date:</b>
  <%= @task.due_date %>
</p>

<% if @task.project %>
  <p>
    <b>Project:</b>
    <%= @task.project.name %>
  </p>
<% end %>

<% if @task.zone %>
  <p>
    <b>Zone:</b>
    <%= @task.zone.name %>
  </p>
<% end %>
<p>
  <b>Done:</b>
  <%= @task.done %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
  <% if @zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% @zone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :name %>
    <div class="input">
      <%= f.text_field :name %>      
    </div>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn primary" %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<h1>Listing zones</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zones.each do |zone| %>
  <tr>
    <td><%= zone.name %></td>
    <td><%= link_to 'Show', zone %></td>
    <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
    <td><%= link_to 'Destroy', zone, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<h1>New zone</h1>

<%= render 'form' %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @zone.name %></h2>

<table>
  <tr>
    <th></th>
    <th></th>
    <th>Due date</th>
    <th>Project</th>
    <th>Zone</th>
    <th></th>
    <th></th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <th>
        <% if task.done? %>
          [&#10003;]
        <% else %>
          <%= link_to "[ ]", complete_task_path(:id => task.id) %>
        <% end %>
      </th>

      <td><%= task.name %></td>
      <td>
        <% if task.due_date.past? %>
          <%= time_ago_in_words(task.due_date) %> ago
        <% else %>
          in <%= time_ago_in_words(task.due_date) %>
        <% end %>
      </td>
      <td><%= link_to(task.project.name, task.project) if task.project %></td>
      <td><%= link_to(task.zone.name, task.zone) if task.zone %></td>
      <td><%= link_to 'Edit', edit_task_path(task) %></td>
      <td><%= link_to 'Delete', task, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>